name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.5
        uses: actions/setup-node@v2
        with:
          node-version: 17.5
      - name: Client
        run: yarn --cwd client install && yarn --cwd client test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy ./server"
      - uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy ./client"
